### PR TITLE
trurl: make '{scheme}\{user}' work

### PR DESCRIPTION
**Pull request by emanuele6**
trurl: support \\\\ in -g formats

This allows e.g. printing 'imap\\new' with  -g '{host}\\\\new'.
It was previously not possible to print a literal backslash followed by
a n/t/r with -g.

---

trurl: make '{scheme}\\{user}' work

Before this patch, the sequence \`\\{' was handled by printing a literal
backslash followed by a literal {.

This was a bit awkward since you are supposed to be using \`{{' to escape
a { character, not \\. Also because the backslash was still being
printed.

With this patch \`\\{' is now handled by only printing a backslash, and
then handling the next character, instead of printing it
indiscrimintately.

So, now,   trurl -g '{scheme}\\{user}' gopher://emanuele6@locahost/
outputs   gopher\\emanuele6   instead of   gopher\\{user}   .

The previous commit that added support for \`\\\\' makes this change less
necessary since the user should have used   {scheme}\\\\{user}   instead
of using a single backslash, but I still think this behaviour makes more
sense, and may prevent future bugs.

### CODE REVIEW

**Comment by emanuele6** [comment]
fixup: changed `++ptr` to `ptr++` for consistency with the rest of the code.

**Comment by emanuele6** [comment]
I learned about those backslash sequence, and `{{` only after reading the source code, because I noticed that `-g '\{scheme}'` printed `\{scheme}` literally when playing with powershell for #129.
I didn't know about them because they are not documented.

The addition of `\\` with the first commit, really makes the second commit unnecessary since it would only change the behaviour of `\unknown` which, I assume, at least once those backslash sequences will be documented, will be unspecified.

The current way `trurl` handles unknown sequences is printing both the backslash character and the following character literally, and then handling the second character after the backslash. This way `\s` for example, is still printed as `\s` as if `\\s` was used.

A side effect of the current implementation is that `\{host}` is equivalent to `\\{{host}`, since the code skips the `{` following the backslash and prints it indiscriminately, which I find weird. So, I changed the behaviour of `\unknown` to make it equivalent to `\\unknown` which was probably the behaviour that was originally intended.

**Comment by bagder** [comment]
I think the backslash handling should work like the `printf` command line tool. Not introduce a new way of working. For \-[unknown symbol] it outputs both the backslash and the symbol:

~~~
$ printf '\\ hello \{\n'
\ hello \{
~~~

where as with this PR, trurl hides the unknown symbol:
~~~
$ ./trurl localhost -g '{host} \\ hej \{ moo \'
localhost \ hej \ moo \
~~~

**Comment by emanuele6** [comment]
> where as with this PR, trurl hides the unknown symbol:
>
> ```
> $ ./trurl localhost -g '{host} \\ hej \{ moo \'
> localhost \ hej \ moo \
> ```

That is not supposed to happen; I think this is an existing bug with unterminated `{component}` expansions:
```
$ ./trurl localhost -g '{foo'
foo
```

**Comment by emanuele6** [comment]
Closing in favour of #133

**Pull request closed without merging**
