### PR TITLE
trurl: output JSON as an array

### LINKED ISSUE #49: multiple URL JSON output?
How is the JSON format supposed to look like when trurl outputs multiple objects?

Right now it looks like this when given 4 URLs:
~~~
$ cat urls.txt | ./trurl --json -f -
{
  "url": "http://localhost/",
  "scheme": "http",
  "host": "localhost",
  "port": "80",
  "path": "/",
}
{
  "url": "http://haxx.se/",
  "scheme": "http",
  "host": "haxx.se",
  "port": "80",
  "path": "/",
}
{
  "url": "https://curl.se/",
  "scheme": "https",
  "host": "curl.se",
  "port": "443",
  "path": "/",
}
{
  "url": "http://curl.haxx.se/",
  "scheme": "http",
  "host": "curl.haxx.se",
  "port": "80",
  "path": "/",
}

### PR DESCRIPTION
**Pull request by bagder**
To properly work with many URLs

Fixes #49

### CODE REVIEW

**Comment by bagder** [comment]
Test code from #53 by @paulroub

**Comment by bagder** [comment]
@paulroub you good with going with my patch + your test code?

**Comment by paulroub** [comment]
> @paulroub you good with going with my patch + your test code?

Absolutely!

**Comment by bagder** [comment]
Thanks!

**Pull request merged**
