### PR TITLE
feat(test.py)

### PR DESCRIPTION
**Pull request by sevehub**
test.pl equivalent python script extended for Windows/Mingw64-w64 toolchain.

### CODE REVIEW

**Comment by bagder** [comment]
But why do we need the tests run by python?

**Comment by sevehub** [comment]
I think it's just more convenient to have a Python test script when you compile the program on Windows (Mingw64-w64).
Decided to share it in case you need it.

**Comment by bagder** [comment]
Doesn't it run perl scripts just as easily?

I think we should separate the test data from the test runner, then I'm fine with having it in python if that is easier for some reason. But I don't think we need two separate ones.

**Comment by sevehub** [comment]
I am sure it does, but I have no idea how to write platform-independent Perl scripts.

I can move the test urls inside a csv file (test.csv), haven't seen commas used within the program's options.
Better close this PR and submit a new one.

**Comment by bagder** [comment]
I think we should expand the test file format at once. It also needs to be able to verify the exit code and multi-line outputs.

**Comment by sevehub** [comment]
Multilines are still single lines with a bunch of line separators in them.
Format can be something like:
input, output, exit code
--url https://curl.se?name=hello --append query=search=string, https://curl.se/?name=hello&search=string, 0

**Comment by sevehub** [comment]
Second thought, I have seen the ongoing PR.
We can copy the test data inside a JSON file, would it be possible to have a dedicated branch?

**Comment by bagder** [comment]
> We can copy the test data inside a JSON file

As long as the tests remain easy to make and read, I don't mind JSON.

> would it be possible to have a dedicated branch?

Please elaborate. Why do we want a branch?

**Comment by sevehub** [comment]
It's ok, I will use the master branch.
I close this commit meanwhile.

**Pull request closed without merging**
