### PR TITLE
Makefile: switch to using test.py

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by bagder** [comment]
@havbon it seems this does not work very well on cygwin?

**Comment by havbon** [comment]
Thats really strange, it worked for me. I am not available atm so i cant test.

Could you try to remove "3" from Python in the makefile? "@python test.py"

**Comment by bagder** [comment]
> Could you try to remove "3" from Python in the makefile? "@python test.py"

Not easily. On debian:
~~~
$ python
bash: python: command not found

**Comment by havbon** [comment]
Hmm okay, ill do some testing in a bit. I was thinking maybe adding python3 as a package on cygwin?

**Comment by havbon** [comment]
adding `python39` to cygwin packages in `makefile.yml` worked.

`packages: curl, libcurl-devel, libcurl4, make, gcc-core, python39`

**Pull request closed without merging**
