### PR TITLE
make --json output query pairs under "params"

### PR DESCRIPTION
**Pull request by bagder**
A take at fixing #90, but I'm not sure of the syntax. Also, no handling of multiple identical keys yet.

### CODE REVIEW

**Comment by emanuele6** [comment]
URLs can technically contain two query entries with the same key.
`trurl --json` will output a URL with two query entries with the same keys as:
```bash
bash-5.1$ trurl --json 'example.org?x=1&v=3&x=2'
[
kk
  {
    "url": "http://example.org/?x=1&x=2",
    "scheme": "http",
    "host": "example.org",
    "port": "80",
    "path": "/",
    "query": "x=1&x=2",
    "q": {
      "x": "1",
      "v": "3",
      "x": "2"
    }
  }
]
```
Technically this is valid JSON, it is valid to have two entries in a JSON object with the same key, but most JSON parsing libraries/tools ignore this detail, and just keep one of the two values:
```
bash-5.1$ trurl --json 'example.org?q=1&v=3&q=2' | python -c 'import json, sys; print(json.dumps(json.load(sys.stdin)))'
[{"url": "http://example.org/?q=1&v=3&q=2", "scheme": "http", "host": "example.org", "port": "80", "path": "/", "query": "q=1&v=3&q=2", "q": {"q": "2", "v": "3"}}]
bash-5.1$ trurl --json 'example.org?x=1&v=3&x=2' | jq
[
  {
    "url": "http://example.org/?x=1&v=3&x=2",
    "scheme": "http",
    "host": "example.org",
    "port": "80",
    "path": "/",
    "query": "x=1&v=3&x=2",
    "q": {
      "x": "2",
      "v": "3"
    }
  }
]
bash-5.1$ trurl --json 'example.org?x=1&v=3&x=2' > foo.json; node -p 'JSON.stringify(require("./foo.json"))'
[{"url":"http://example.org/?q=1&v=3&q=2","scheme":"http","host":"example.org","port":"80","path":"/","query":"q=1&v=3&q=2","q":{"q":"2","v":"3"}}]
```

Maybe we could use a format like `"q": { "x": [ 1, 2 ], "y": 3 }` or `"q": [{"key":"x","value":"1"},{"key":"y","value":"3"},{"key":"x","value":"2"}` instead.

Also, even though, that JSON is technically valid, the JSON specification does not give meaning to the order of entries in a JSON object.

If the order of `v=2&x=10` vs `x=10&v=2` matters, then only the array of key-value pairs solution works.

I am not sure if this matters much.

**Comment by emanuele6** [comment]
For what is worth, the javascript interface to parse query strings mentioned in #100 that is also available in `node`, returns a ordered collection of key value pair \(like `"params": [{"key":"x","value":"1"},{"key":"y","value":"3"},{"key":"x","value":"2"}]`\):
```bash
bash-5.1$ node -p 'new URLSearchParams(process.argv[1])' 'foo=1&bar=2&x&y&x&foo=3'
URLSearchParams { 'foo' => '1', 'bar' => '2', 'x' => '', 'y' => '', 'x' => '', 'foo' => '3' }
```

`python`'s builtin URL parsing library has returns a list of key-value tuples:
```bash
bash-5.1$ python -c 'import sys, urllib.parse; print(urllib.parse.parse_qsl(sys.argv[1], keep_blank_values=True))' 'foo=1&bar=2&x&y&x&foo=3'
[('foo', '1'), ('bar', '2'), ('x', ''), ('y', ''), ('x', ''), ('foo', '3')]
```
But it also provides an alternate convenience function that returns an unordered dictionary dictionary of keys to ordered list of values \(like `"params": { "x": [ 1, 2 ], "y": 3 }`\):
```bash
bash-5.1$ python -c 'import sys, urllib.parse; print(urllib.parse.parse_qs(sys.argv[1], keep_blank_values=True))' 'foo=1&bar=2&x&y&x&foo=3'
{'foo': ['1', '3'], 'bar': ['2'], 'x': ['', ''], 'y': ['']}
```

**Comment by emanuele6** [comment]
I think the `URLSearchParams`/`urllib.parse.parse_qsl` way is the most correct output format.

So for the URL in the previous example, `trurl` would output something like:
```bash
bash-5.1$ trurl --json 'example.org?x=1&v=3&x=2'
[
  {
    "url": "http://example.org/?x=1&v=3&x=2",
    "scheme": "http",
    "host": "example.org",
    "port": "80",
    "path": "/",
    "query": "x=1&v=3&x=2",
    "params": [
      {
        "key": "x",
        "value": "1"
      },
      {
        "key": "v",
        "value": "3"
      },
      {
        "key": "x",
        "value": "2"
      }
    ]
  }
]
```

"key"/"value" could be shortened to "k"/"v", but I think "key"/"value" is better because it is compatible with `jq`'s `from_entries` function, so users can easily write a jq command like `jq '.[].params |= from_entries'` if they want to convert "params" to an object.
```bash
bash-5.1$ jq '.[].params |= from_entries' << 'EOF'
[
  {
    "url": "http://example.org/?x=1&v=3&x=2",
    "scheme": "http",
    "host": "example.org",
    "port": "80",
    "path": "/",
    "query": "x=1&v=3&x=2",
    "params": [
      {
        "k": "x",
        "v": "1"
      },
      {
        "k": "v",
        "v": "3"
      },
      {
        "k": "x",
        "v": "2"
      }
    ]
  }
]
EOF
jq: error (at <stdin>:24): Cannot use null (null) as object key
```
```bash
bash-5.1$ jq '.[].params |= from_entries' << 'EOF'
[
  {
    "url": "http://example.org/?x=1&v=3&x=2",
    "scheme": "http",
    "host": "example.org",
    "port": "80",
    "path": "/",
    "query": "x=1&v=3&x=2",
    "params": [
      {
        "key": "x",
        "value": "1"
      },
      {
        "key": "v",
        "value": "3"
      },
      {
        "key": "x",
        "value": "2"
      }
    ]
  }
]
EOF
[
  {
    "url": "http://example.org/?x=1&v=3&x=2",
    "scheme": "http",
    "host": "example.org",
    "port": "80",
    "path": "/",
    "query": "x=1&v=3&x=2",
    "params": {
      "x": "2",
      "v": "3"
    }
  }
]
```

**Comment by bagder** [comment]
Switched to the params and key/value approach

**Comment by bagder** [comment]
So maybe I should proceed and merge this and let everyone have a try and see how it runs?

**Pull request closed without merging**
