### PR TITLE
trurl: support "--" end-of-options argument

### PR DESCRIPTION
**Pull request by emanuele6**

### CODE REVIEW

**Comment by emanuele6** [comment]
Fixes #102

**Comment by bagder** [comment]
But what's the point? To allow the user to provide a URL that starts with a dash that won't work?

**Comment by emanuele6** [comment]
@bagder they will work, you can see it with `-f -` or `--url`:
```bash
bash-5.1$ printf %s\\n --json | ./trurl -f -
http://--json/
bash-5.1$ trurl --url --json
http://--json/
```
The parser will guess it is a `http` URL.

But that is not main reason why I would like this; if I get multiple URLs to process from an unknow source, to process them with trurl,I will have to either loop over them, and construct a second list of arguments that has a `--url` argument for each one:

```bash
urls=( example.org -a query=destination=notme curl.se/trurl ) # hardoded for this example
trurl_args=()
for url in "${urls[@]}"; do
     trurl_args+=( --url "$url" )
done
trurl --json "${trurl_args[@]}"
```

Invoke trurl multiple times so I can easily use `--url`, and use another tool to join the output together (with this approach I lose the ability to easily use `--verify` or check the exit code of trurl without adding extra code):
```bash
urls=( example.org -a query=destination=notme curl.se/trurl ) # hardoded for this example
for url in "${urls[@]}"; do
    trurl --json --url "$url"
done |
jq -s 'add'
```

If I am 100% elements of `${urls[@]}` will not contain newline, and will not be empty, or I loop to the array to verify that is true and discard elements that contain newline or are empty, I can use:
```bash
urls=( example.org -a query=destination=notme curl.se/trurl ) # hardoded for this example
for i in "${!urls[@]}"; do
    case ${urls[i]} in
        ''|*$'\n'*) unset -v 'urls[i]' # or maybe abort
    esac
done
urls=( "${urls[@]}" )
printf %s\\n | trurl --json -f -
```

And finally, only if I am 100% elements of `${urls[@]}` will not start with "-", or I can loop the array to verify that that is true, and discard elements that start with "-" (assuming I don't want to keep them), I can use:
```bash
trurl --json "$@"
```

It would be much nicer if as user I would not have to do this verification, filtering or plumbing before calling `trurl`, and I could just use `--` safely:
```bash
trurl --json -- "$@"
```

**Comment by bagder** [comment]
Well, you could just do `trurl --json --url "${urls[@]}"` to fix that issue, but okay. I can accept this change as it might make sense for some.

**Review by bagder — APPROVED** [review]

**Comment by emanuele6** [comment]
Thank you!

To clarify `--url "${urls[@]}"` would only solve the problem for the first element of the array:

```
~/trurl $ urls=( --version example.org -a query=destination=notme curl.se/trurl )
~/trurl $ trurl "${urls[@]}"                                                trurl version 0.3 libcurl/7.88.0
~/trurl $ trurl --url "${urls[@]}"
http://--version/?destination=notme
http://example.org/?destination=notme
http://curl.se/trurl?destination=notme
~/trurl $ trurl -- "${urls[@]}"
http://--version/
http://example.org/
http://-a/
trurl note: Bad hostname [query=destination=notme]
http://curl.se/trurl
```

**Pull request merged**
